import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import face1 from '@/../public/images/face1.jpg'
import face2 from '@/../public/images/face2.jpg'
import face3 from '@/../public/images/face3.jpg'
import Btn from '@/../public/images/btn.jpg'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head key={2}>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
        <div className={styles.sub_grid_1}>
          <div className={styles.grid_item}>
            <Image src={face1} title="face" alt="face"/>
            <div className={styles.sub_grid}>
              <h4>Jean Doe</h4>
              <h5>User Experence Designer</h5>
            </div>
            <a href={"/0"}><Image src={Btn} title="Icon Button" alt="face"/></a>
            <p>Jean is a experenced designer, specialized in system design components</p>
          </div>
          <div className={styles.grid_item}>
            <Image src={face1} title="face" alt="face"/>
            <div className={styles.sub_grid}>
              <h4>Jean Doe</h4>
              <h5>User Experence Designer</h5>
            </div>
            <a href={"/0"}><Image src={Btn} title="Icon Button" alt="face" /></a>
            <p>Jean is a experenced designer, specialized in system design components</p>
          </div>
        </div>
        <div className={styles.sub_grid_2}>
        <div className={styles.grid_item}>
            <Image src={face2} title="face" alt="face"/>
            <div className={styles.sub_grid}>
              <h4>Jean Doe</h4>
              <h5>User Experence Designer</h5>
            </div>
            <a href={"/0"}><Image src={Btn} title="Icon Button" alt="face"/></a>
            <p>Jean is a experenced designer, specialized in system design components</p>
          </div>
          <div className={styles.grid_item}>
            <Image src={face2} title="face" alt="face"/>
            <div className={styles.sub_grid}>
              <h4>Jean Doe</h4>
              <h5>User Experence Designer</h5>
            </div>
            <a href={"/0"}><Image src={Btn} title="Icon Button" alt="face"/></a>
            <p>Jean is a experenced designer, specialized in system design components</p>
          </div>
          <div className={styles.grid_item}>
            <Image src={face2} title="face" alt="face"/>
            <div className={styles.sub_grid}>
              <h4>Jean Doe</h4>
              <h5>User Experence Designer</h5>
            </div>
            <a href={"/0"}><Image src={Btn} title="Icon Button" alt="face"/></a>
            <p>Jean is a experenced designer, specialized in system design components</p>
          </div>
        </div>
        <div className={styles.sub_grid_3}>
        <div className={styles.grid_item}>
            <Image src={face3} title="face" alt="face"/>
            <div className={styles.sub_grid}>
              <h4>Jean Doe</h4>
              <h5>User Experence Designer</h5>
            </div>
            <a href={"/0"}><Image src={Btn} title="Icon Button" alt="face"/></a>
            <p>Jean is a experenced designer, specialized in system design components</p>
          </div>
          <div className={styles.grid_item}>
            <Image src={face3} title="face" alt="face"/>
            <div className={styles.sub_grid}>
              <h4>Jean Doe</h4>
              <h5>User Experence Designer</h5>
            </div>
            <a href={"/0"}><Image src={Btn} title="Icon Button" alt="face"/></a>
            <p>Jean is a experenced designer, specialized in system design components</p>
          </div>
          <div className={styles.grid_item}>
            <Image src={face3} title="face" alt="face" />
            <div className={styles.sub_grid}>
              <h4>Jean Doe</h4>
              <h5>User Experence Designer</h5>
            </div>
            <a href={"/0"}><Image src={Btn} title="Icon Button" alt="face"/></a>
            <p>Jean is a experenced designer, specialized in system design components</p>
          </div>
          <div className={styles.grid_item}>
            <Image src={face3} title="face" alt="face"/>
            <div className={styles.sub_grid}>
              <h4>Jean Doe</h4>
              <h5>User Experence Designer</h5>
            </div>
            <a href={"/0"}><Image src={Btn} title="Icon Button" alt="face"/></a>
            <p>Jean is a experenced designer, specialized in system design components</p>
          </div>
        </div>
        </div>
      </main>
    </>
  )
}
